# Generated by Django 4.0.4 on 2022-05-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnMask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='latitude',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='longitude',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
