# Generated by Django 4.0.4 on 2022-05-30 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UnMask', '0002_alter_users_latitude_alter_users_longitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
    ]
