# Generated by Django 4.0.4 on 2022-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnMask', '0006_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_men',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_women',
            field=models.BooleanField(default=False),
        ),
    ]
