# Generated by Django 4.0.4 on 2022-06-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnMask', '0007_alter_profile_interested_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='UnMask.profile'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='UnMask.profile'),
        ),
    ]
