# Generated by Django 4.0.4 on 2022-06-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnMask', '0008_alter_matches_user1_alter_matches_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
