# Generated by Django 4.0.4 on 2022-06-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnMask', '0010_matches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='user1_match',
            new_name='profile1_match',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='user2_match',
            new_name='profile2_match',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='user2',
        ),
        migrations.AddField(
            model_name='matches',
            name='profile1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='UnMask.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matches',
            name='profile2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='UnMask.profile'),
            preserve_default=False,
        ),
    ]
